import Head from 'next/head'
import Offers from '../../components/Offers'

export default function OfferPage() {
  return (
    <div>
      <Head>
        <title>Front Ofertas</title>
        <meta name="theme-color" content="var(--theme)" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Offers/>
    </div>
  )
}
